version: '3'

networks:
  appnet:

services:
  mysql:
    image: mysql:5.7.29
    container_name: mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_USER: foss
      MYSQL_DATABASE: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - appnet
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      APP_NAME: Linkdoni
      APP_URL: http://FOLAN.com #APP URL HERE
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: foss
      DB_PASSWORD: secret
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mysql 
    networks:
      - appnet
